spring.application.name=test-management-api

# ===============================================
# H2 DATABASE CONFIGURATION
# ===============================================

## This is the connection URL for the H2 in-memory database.
## "testdb" will be the name of our database.
#spring.datasource.url=jdbc:h2:mem:testdb
#
## The username for the H2 database. 'sa' is the standard default.
#spring.datasource.username=sa
#
## The password for the H2 database. We can leave it blank for H2.
#spring.datasource.password=
#
## This tells Spring Boot which driver to use to talk to the database.
#spring.datasource.driverClassName=org.h2.Driver
#
#
## ===============================================
## H2 CONSOLE CONFIGURATION
## ===============================================
#
## This enables the web-based H2 console.
#spring.h2.console.enabled=true
#
## This sets the URL where we can access the console.
## It's good practice to change this from the default '/h2-console' for security.
#spring.h2.console.path=/h2-ui


#=========================================
#MYSQL CONFIGUATION
spring.datasource.url=jdbc:mysql://localhost:3306/testportal_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# ===============================================
# JPA (DATABASE MAPPING) CONFIGURATION
# ===============================================

# This line tells JPA (through Hibernate) to automatically create, and update
# our database tables based on our @Entity classes.
# This is incredibly useful for development.
spring.jpa.hibernate.ddl-auto=update


# This will show the actual SQL queries that JPA is running in the console logs.
# It's very helpful for debugging and learning.
spring.jpa.show-sql=true


#Jwt
app.jwt.secret=S3cr3tK3yF0rT3stM4n4g3m3ntP0rt4lV3ryL0ngAndS3cur3Ind33d1234567890!@#

# Expiration time for the JWT in milliseconds. 86400000ms = 24 hours.
app.jwt.expiration-ms=86400000

#Google auth token
app.google.client-id=713000365254-jo55s5h614h6g4f5vr3rpob3atvi9vb9.apps.googleusercontent.com