## ===============================================
## PRODUCTION DATABASE (NEON POSTGRES)
## ===============================================
## We use ${VAR_NAME} to read these from Render's settings later
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA Configuration for Postgres
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#
## ===============================================
## JWT CONFIGURATION
## ===============================================
#app.jwt.secret=${JWT_SECRET}
#app.jwt.expiration-ms=86400000


#==================

# ===============================================
# PRODUCTION DATABASE (AWS RDS MySQL)
# ===============================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration for MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================================
# JWT CONFIGURATION
# ===============================================
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

# ===============================================
# GOOGLE AUTH (Production)
# ===============================================
app.google.client-id=${GOOGLE_CLIENT_ID:713000365254-jo55s5h614h6g4f5vr3rpob3atvi9vb9.apps.googleusercontent.com}